### ISSUE TITLE
check for laravel version above v9.32.0

### ISSUE THREAD

**Issue by alissn** [glhd/laravel-dumper#13]
hi, 

before v9.32.0 when dd( Illuminate\Database\Eloquent\Builder ) show query, and it's very useful

after update don't show query and just return  Illuminate\Database\Eloquent\Builder class attribute

I guess something changed and affected this.

**Comment by giagara** [comment]
I think this is related to [this](https://github.com/laravel/framework/pull/44211)

**Comment by inxilpro** [comment]
Yeah, the new `dd()` behavior has impacted this package. I'm hoping to [get it into core](https://github.com/laravel/framework/pull/44408), but either way, I'll try to sort out something.

**Comment by alissn** [comment]
Hi @inxilpro,

Is it possible for you to update this package to be usable in Laravel version 10?

This package is very useful for debugging and saving time, as it makes data more readable. Despite the addition of the new method `ddRawSql`, it does not format the output in the same way as this package. I don't think it would be advisable to add the `jdorn/sql-formatter` package to the core of Laravel.

If you have the time, please consider updating this package.

Thanks.

**Comment by inxilpro** [comment]
I think I finally figured out a workaround. Look for an update soon!
