### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by Temepest74** [glhd/laravel-dumper#15]
**Describe the bug**
Just doing thins
```php
        dd(User::all());
```
and it does not work, i get all the useless info

**What version does this affect?**
 - Laravel Version: latest Laravel 10
 - Package Version: 1.1.0

**Comment by xHeaven** [comment]
+1, I just tried it because the idea seems pretty neat, however, it doesn't do anything at all. It seems like there was an update in Laravel that practically killed this package.

**Comment by inxilpro** [comment]
Should be fixed in the next version.
