### ISSUE TITLE
Add sample of each enhanced dumper vs original output

### ISSUE THREAD

**Issue by hailwood** [glhd/laravel-dumper#2]
This package is pretty awesome! Great work.

I think it would help the uptake if we could add some way to show the improvement of each dumper.
Ideas are
- Videos like on the readme
- Screenshots of the top parts
- Directory of e.g. query_builder_original.txt and query_builder_enhanced.txt

**Comment by inxilpro** [comment]
Great idea! I just added [a bunch of diffs to the repo](https://github.com/glhd/laravel-dumper/tree/main/diffs)
