### ISSUE TITLE
Installation issue PHP < 8.0

### ISSUE THREAD

**Issue by akawam** [glhd/laravel-dumper#5]
Hello,

When running composer require, if PHP is below 8.0, it will throw an error during `@php artisan package:discover` because of typed properties.

I would recommand upgrading composer.json with the minimum php version or update classes to make it compatible as it should not be a breaking change

Regards

**Comment by inxilpro** [comment]
What version of PHP are you using? It should be fine with PHP 7.4 and above…

**Comment by inxilpro** [comment]
Here's the most recent test run at PHP 7.4:

https://github.com/glhd/laravel-dumper/runs/5037553044?check_suite_focus=true

**Comment by inxilpro** [comment]
I'm going to close this for now. Feel free to reply if you run into this again.
